# Generated by Django 5.1.5 on 2025-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poste',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
