# Generated by Django 5.1.5 on 2025-01-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0002_user_is_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_connected',
        ),
    ]
