# Generated by Django 5.1.5 on 2025-01-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0002_user_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='statut_fumeur',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
