# Generated by Django 5.1.5 on 2025-01-29 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0003_alter_user_date_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='charges',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_souscription',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 21, 9, 23, 584952), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='imc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_operateur',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_prospect',
            field=models.BooleanField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre_enfant',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='poids',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='poste',
            field=models.CharField(default='Courtier', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='statut_fumeur',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='taille',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
