# Generated by Django 5.1.5 on 2025-01-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0003_remove_user_is_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='Date_heure',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='heure',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='poste',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(default='female', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='statut_fumeur',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
