# Generated by Django 5.1.5 on 2025-01-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0003_alter_user_sexe_alter_user_statut_fumeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='charges',
            field=models.FloatField(null=True),
        ),
    ]
