# Generated by Django 5.1.5 on 2025-01-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0004_alter_user_age_alter_user_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_souscription',
            field=models.DateTimeField(null=True),
        ),
    ]
