# Generated by Django 5.1.5 on 2025-01-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0004_user_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
