# Generated by Django 5.1.5 on 2025-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0004_remove_rendezvous_date_heure_rendezvous_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
