# Generated by Django 5.1.5 on 2025-01-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0005_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombre_enfant',
            field=models.IntegerField(null=True),
        ),
    ]
