# Generated by Django 5.1.5 on 2025-01-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0005_alter_user_date_souscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_de_naissance',
            field=models.DateField(default='1970-01-01', null=True),
        ),
    ]
