# Generated by Django 5.1.5 on 2025-01-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0006_user_nombre_enfant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='statut_fumeur',
            new_name='status_fumeur',
        ),
    ]
