# Generated by Django 5.1.5 on 2025-01-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0006_remove_rendezvous_id_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='operateur',
            field=models.CharField(default='opérateur 1', max_length=150),
        ),
    ]
