# Generated by Django 5.1.5 on 2025-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0007_alter_rendezvous_operateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='heure',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_heure',
            field=models.DateTimeField(null=True),
        ),
    ]
