# Generated by Django 5.1.5 on 2025-01-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0007_rename_statut_fumeur_user_status_fumeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status_fumeur',
            new_name='statut_fumeur',
        ),
    ]
