# Generated by Django 5.1.5 on 2025-01-29 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0008_remove_rendezvous_date_remove_rendezvous_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='operateur',
            field=models.ForeignKey(limit_choices_to={'is_operateur': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='type',
            field=models.CharField(choices=[('physique', 'Physique'), ('telephone', 'Téléphone'), ('visio', 'Visio')], max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='rendezvous',
            constraint=models.UniqueConstraint(fields=('operateur', 'date_heure'), name='unique_rdv_operateur'),
        ),
    ]
