# Generated by Django 5.1.5 on 2025-01-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0009_alter_user_region_alter_user_sexe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='poste',
            field=models.CharField(blank=True, choices=[('courtier', 'Courtier'), ('manager', 'Manager')], max_length=10, null=True),
        ),
    ]
