# Generated by Django 5.1.5 on 2025-01-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0010_alter_user_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imc',
            field=models.FloatField(null=True),
        ),
    ]
