# Generated by Django 5.1.5 on 2025-01-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0011_alter_user_imc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('northwest', 'Northwest'), ('northeast', 'Northeast'), ('southwest', 'Southwest'), ('southeast', 'Southeast')], max_length=20, null=True),
        ),
    ]
